packages:
  - packages/*
  - themes/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks

catalog:
    '@clack/prompts': ^0.11.0
    '@preact/preset-vite': ^2.10.2
    '@tailwindcss/vite': ^4.1.13
    '@vitest/ui': ^3.2.4
    bumpp: ^10.2.3
    esno: ^0.14.1
    jsdom: ^26.1.0
    lint-staged: ^16.1.6
    picocolors: ^1.1.1
    sass: ^1.92.1
    simple-git-hooks: ^2.13.1
    stylelint: 16.23.1
    stylelint-config-standard: 39.0.0
    stylelint-order: 7.0.0
    stylelint-selector-bem-pattern: 4.0.1
    tailwindcss: ^4.1.13
    taze: ^19.6.0
    terser: ^5.44.0
    tsdown: latest
    tw-animate-css: ^1.3.8
    typescript: ^5.9.2
    vite-bundle-analyzer: latest
    vitest: ^3.2.4
    '@iconify-json/carbon': ^1.2.13
    canvas-confetti: ^1.9.3
    class-variance-authority: ^0.7.1
    lucide: ^0.544.0
    lucide-preact: ^0.544.0
    notyf: ^3.10.0
    preact: ^10.26.9
    prettier: ^3.6.2
    unocss: ^0.28.3
    vue: ^3.5.21
    '@vitejs/plugin-vue': ^2.3.4
    unplugin-vue-components: ^0.18.5
    vite: ^7.1.6
    vite-plugin-html: ^3.2.2
    vite-plugin-pwa: ^0.11.13
    vite-plugin-singlefile: ^2.3.0
    '@types/jquery': ^3.5.33
    '@types/node': ^24.5.2
    vite-plugin-svgr: ^4.5.0
    "@biomejs/biome": "^2.2.4"
    "clsx": "^2.0.0"
    "tailwind-merge": "^2.0.0"
    "sonner": "^2.0.7"
    "lefthook": "^1.13.6"
