packages:
  - packages/*
  - themes/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@clack/prompts': ^0.11.0
  '@iconify-json/carbon': ^1.2.14
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.5.0
  '@tailwindcss/vite': ^4.1.17
  '@types/cross-spawn': ^6.0.6
  '@types/jquery': ^3.5.33
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^2.3.4
  '@vitest/ui': ^3.2.4
  bumpp: ^10.3.1
  canvas-confetti: ^1.9.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cross-spawn: ^7.0.6
  es-toolkit: ^1.41.0
  esno: ^0.14.1
  happy-dom: ^20.0.10
  lefthook: ^1.13.6
  lint-staged: ^16.2.6
  lucide: ^0.544.0
  lucide-preact: ^0.544.0
  mri: ^1.2.0
  notyf: ^3.10.0
  picocolors: ^1.1.1
  preact: ^10.27.2
  prettier: ^3.6.2
  sass: ^1.94.0
  simple-git-hooks: ^2.13.1
  stylelint: 16.23.1
  stylelint-config-standard: 39.0.0
  stylelint-order: 7.0.0
  stylelint-selector-bem-pattern: 4.0.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.17
  taze: ^19.9.0
  terser: ^5.44.1
  tsdown: latest
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  unocss: ^0.28.3
  unplugin-vue-components: ^0.18.5
  vite: ^7.2.2
  vite-bundle-analyzer: latest
  vite-plugin-html: ^3.2.2
  vite-plugin-pwa: ^0.11.13
  vite-plugin-singlefile: ^2.3.0
  vite-plugin-svgr: ^4.5.0
  vitest: ^3.2.4
  vue: ^3.5.24

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - simple-git-hooks
