declare module '@tona/plugins' {
  export function musicPlayer(theme: any, devOptions?: any): void
  export function background(theme: any, devOptions?: any): void
  export function barrage(theme: any, devOptions?: any): void
  export function catalog(theme: any, devOptions?: any): void
  export function charts(theme: any, devOptions?: any): void
  export function clickEffects(theme: any, devOptions?: any): void
  export function codeCopy(theme: any, devOptions?: any): void
  export function codeHighlight(theme: any, devOptions?: any): void
  export function codeLang(theme: any, devOptions?: any): void
  export function codeLinenumbers(theme: any, devOptions?: any): void
  export function codeTrafficLight(theme: any, devOptions?: any): void
  export function colorMode(theme: any, devOptions?: any): void
  export function commentsAvatars(theme: any, devOptions?: any): void
  export function darkMode(theme: any, devOptions?: any): void
  export function donation(theme: any, devOptions?: any): void
  export function emoji(theme: any, devOptions?: any): void
  export function footer(theme: any, devOptions?: any): void
  export function imagePreview(theme: any, devOptions?: any): void
  export function license(theme: any, devOptions?: any): void
  export function live2d(theme: any, devOptions?: any): void
  export function lock(theme: any, devOptions?: any): void
  export function notation(theme: any, devOptions?: any): void
  export function notice(theme: any, devOptions?: any): void
  export function postBottomImage(theme: any, devOptions?: any): void
  export function postMessage(theme: any, devOptions?: any): void
  export function postTopImage(theme: any, devOptions?: any): void
  export function qrcode(theme: any, devOptions?: any): void
  export function signature(theme: any, devOptions?: any): void
  export function tools(theme: any, devOptions?: any): void
  export function webTag(theme: any, devOptions?: any): void
}
