type TechStack = {
  title: string
  href: string
  categories: string[]
  lightIcon: string
  darkIcon?: string
}

const BASE_URL = 'https://blog-static.cnblogs.com/files/guangzan/'

export const TECH_STACK: TechStack[] = [
  {
    title: 'TypeScript',
    href: 'https://www.typescriptlang.org/',
    categories: ['Language'],
    lightIcon: `${BASE_URL}typescript.svg`,
  },
  {
    title: 'Go',
    href: 'https://go.dev/',
    categories: ['Language'],
    lightIcon: `${BASE_URL}go.svg`,
  },
  {
    title: 'Java',
    href: 'https://www.java.com/',
    categories: ['Language'],
    lightIcon: `${BASE_URL}java.svg`,
  },
  {
    title: 'React',
    href: 'https://react.dev/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}react-light.svg`,
    darkIcon: `${BASE_URL}react-dark.svg`,
  },
  {
    title: 'Vue',
    href: 'https://vuejs.org/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}vue.svg`,
  },
  {
    title: 'Preact',
    href: 'https://preactjs.com/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}preact.svg`,
  },
  {
    title: 'Next.js',
    href: 'https://nextjs.org/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}nextjs-light.svg`,
    darkIcon: `${BASE_URL}nextjs-dark.svg`,
  },
  {
    title: 'Nuxt',
    href: 'https://nuxt.com/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}nuxt.svg`,
  },
  {
    title: 'NestJS',
    href: 'https://nestjs.com/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}nestjs.svg`,
  },
  {
    title: 'Express',
    href: 'https://expressjs.com/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}express.js-light.svg`,
    darkIcon: `${BASE_URL}express.js-dark.svg`,
  },
  {
    title: 'ElysiaJS',
    href: 'https://elysiajs.com/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}elysiajs.svg`,
  },
  {
    title: 'Flutter',
    href: 'https://flutter.dev/',
    categories: ['Framework'],
    lightIcon: `${BASE_URL}flutter.svg`,
  },
  {
    title: 'Ant Design',
    href: 'https://ant.design/',
    categories: ['UI Library'],
    lightIcon: `${BASE_URL}antd.svg`,
  },
  {
    title: 'Base UI',
    href: 'https://base-ui.com/',
    categories: ['UI Library'],
    lightIcon: `${BASE_URL}base-ui-light.svg`,
    darkIcon: `${BASE_URL}base-ui-dark.svg`,
  },
  {
    title: 'Radix UI',
    href: 'https://www.radix-ui.com/',
    categories: ['UI Library'],
    lightIcon: `${BASE_URL}radix-ui-light.svg`,
    darkIcon: `${BASE_URL}radix-ui-dark.svg`,
  },
  {
    title: 'shadcn/ui',
    href: 'https://ui.shadcn.com/',
    categories: ['UI Library'],
    lightIcon: `${BASE_URL}shadcn-ui-light.svg`,
    darkIcon: `${BASE_URL}shadcn-ui-dark.svg`,
  },
  {
    title: 'Magic UI',
    href: 'https://magicui.design/',
    categories: ['UI Library'],
    lightIcon: `${BASE_URL}magicui.svg`,
  },
  {
    title: 'Pinia',
    href: 'https://pinia.vuejs.org/',
    categories: ['State Management'],
    lightIcon: `${BASE_URL}pinia.svg`,
  },
  {
    title: 'PostgreSQL',
    href: 'https://www.postgresql.org/',
    categories: ['Database'],
    lightIcon: `${BASE_URL}postgresql.svg`,
  },
  {
    title: 'MySQL',
    href: 'https://www.mysql.com/',
    categories: ['Database'],
    lightIcon: `${BASE_URL}mysql-light.svg`,
    darkIcon: `${BASE_URL}mysql-dark.svg`,
  },
  {
    title: 'Redis',
    href: 'https://redis.io/',
    categories: ['Database'],
    lightIcon: `${BASE_URL}redis.svg`,
  },
  {
    title: 'Prisma',
    href: 'https://www.prisma.io/',
    categories: ['Database'],
    lightIcon: `${BASE_URL}prisma-light.svg`,
    darkIcon: `${BASE_URL}prisma-dark.svg`,
  },
  {
    title: 'Drizzle ORM',
    href: 'https://orm.drizzle.team/',
    categories: ['Database'],
    lightIcon: `${BASE_URL}drizzle-orm-light.svg`,
    darkIcon: `${BASE_URL}drizzle-orm-dark.svg`,
  },
  {
    title: 'Vite',
    href: 'https://vitejs.dev/',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}vitejs.svg`,
  },
  {
    title: 'esbuild',
    href: 'https://esbuild.github.io/',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}esbuild.svg`,
  },
  {
    title: 'SWC',
    href: 'https://swc.rs/',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}swc.svg`,
  },
  {
    title: 'Rspack',
    href: 'https://rspack.dev/',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}rspack.svg`,
  },
  {
    title: 'Rolldown',
    href: 'https://rolldown.rs/',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}rolldown.svg`,
  },
  {
    title: 'Turborepo',
    href: 'https://turbo.build/repo',
    categories: ['Build Tool'],
    lightIcon: `${BASE_URL}turborepo-light.svg`,
    darkIcon: `${BASE_URL}turborepo-dark.svg`,
  },
  {
    title: 'Vitest',
    href: 'https://vitest.dev/',
    categories: ['Testing'],
    lightIcon: `${BASE_URL}vitest.svg`,
  },
  {
    title: 'Tailwind CSS',
    href: 'https://tailwindcss.com/',
    categories: ['Styling'],
    lightIcon: `${BASE_URL}tailwindcss.svg`,
  },
  {
    title: 'Sass',
    href: 'https://sass-lang.com/',
    categories: ['Styling'],
    lightIcon: `${BASE_URL}sass.svg`,
  },
  {
    title: 'Node.js',
    href: 'https://nodejs.org/',
    categories: ['Runtime'],
    lightIcon: `${BASE_URL}nodejs.svg`,
  },
  {
    title: 'Bun',
    href: 'https://bun.sh/',
    categories: ['Runtime'],
    lightIcon: `${BASE_URL}bun.svg`,
  },
  {
    title: 'Docker',
    href: 'https://www.docker.com/',
    categories: ['DevOps'],
    lightIcon: `${BASE_URL}docker.svg`,
  },
  {
    title: 'Nginx',
    href: 'https://nginx.org/',
    categories: ['DevOps'],
    lightIcon: `${BASE_URL}nginx.svg`,
  },
  {
    title: 'PM2',
    href: 'https://pm2.keymetrics.io/',
    categories: ['DevOps'],
    lightIcon: `${BASE_URL}pm2.svg`,
  },
  {
    title: 'Better Auth',
    href: 'https://www.better-auth.com/',
    categories: ['Auth'],
    lightIcon: `${BASE_URL}better-auth-light.svg`,
    darkIcon: `${BASE_URL}better-auth-dark.svg`,
  },
  {
    title: 'Motion',
    href: 'https://motion.dev/',
    categories: ['Animation'],
    lightIcon: `${BASE_URL}motion.svg`,
  },
  {
    title: 'VueUse',
    href: 'https://vueuse.org/',
    categories: ['Utilities'],
    lightIcon: `${BASE_URL}vueuse.svg`,
  },
  {
    title: 'Zod',
    href: 'https://zod.dev/',
    categories: ['Tools'],
    lightIcon: `${BASE_URL}zod.svg`,
  },
  {
    title: 'TanStack',
    href: 'https://tanstack.com/',
    categories: ['Tools'],
    lightIcon: `${BASE_URL}tanstack.svg`,
  },
  {
    title: 'PowerShell',
    href: 'https://learn.microsoft.com/powershell/',
    categories: ['Tools'],
    lightIcon: `${BASE_URL}powershell.svg`,
  },
]
