// export { btns } from 'plugins/btns'
// export { back2top } from 'plugins/back2top'
// export { shootInitial } from 'plugins/barrage'
export { default as notice } from 'plugins/notice'
export { default as background } from 'plugins/background'
export { default as catalog } from 'plugins/catalog'
export { default as chart } from 'plugins/chart'
export { default as clickEffect } from 'plugins/clickEffect'
export { default as commentsAvatars } from 'plugins/commentsAvatars'
export { default as copyCode } from 'plugins/copyCode'
export { default as donation } from 'plugins/donation'
export { default as toolMenu } from 'plugins/toolMenu'
export { default as emoji } from 'plugins/emoji'
export { default as footer } from 'plugins/footer'
export { default as highlight } from 'plugins/highlight'
export { default as imagebox } from 'plugins/imagebox'
export { default as linenumbers } from 'plugins/linenumbers'
export { default as live2d } from 'plugins/live2d'
export { default as lock } from 'plugins/lock'
export { default as mode } from 'plugins/mode'
export { default as notation } from 'plugins/notation'
export { default as player } from 'plugins/player'
export { default as postBottomimage } from 'plugins/postBottomimage'
export { default as postMessage } from 'plugins/postMessage'
export { default as postSignature } from 'plugins/postSignature'
export { default as postTopimage } from 'plugins/postTopimage'
export { default as progress } from 'plugins/progress'
export { default as qrcode } from 'plugins/qrcode'
export { default as signature } from 'plugins/signature'
export { default as themeColor } from 'plugins/themeColor'
export { default as titleFavicon } from 'plugins/titleFavicon'
export { default as codeLanguage } from 'plugins/codeLanguage'
