// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./.vitepress/components/Avatar.vue')['default']
    Badge: typeof import('./.vitepress/components/Badge.vue')['default']
    Confetti: typeof import('./.vitepress/components/Confetti.vue')['default']
    Contributors: typeof import('./.vitepress/components/Contributors.vue')['default']
    Guide: typeof import('./.vitepress/components/Guide.vue')['default']
    Home: typeof import('./.vitepress/components/Home.vue')['default']
    Screenshot: typeof import('./.vitepress/components/Screenshot.vue')['default']
    Step1: typeof import('./.vitepress/components/Step1.vue')['default']
    Step2: typeof import('./.vitepress/components/Step2.vue')['default']
    Step3: typeof import('./.vitepress/components/Step3.vue')['default']
    Step4: typeof import('./.vitepress/components/Step4.vue')['default']
    Step5: typeof import('./.vitepress/components/Step5.vue')['default']
    Step6: typeof import('./.vitepress/components/Step6.vue')['default']
    Step7: typeof import('./.vitepress/components/Step7.vue')['default']
    Step8: typeof import('./.vitepress/components/Step8.vue')['default']
    Underline: typeof import('./.vitepress/components/Underline.vue')['default']
  }
}

export { }
